@hostname = "http://localhost:3030/v1/api"
###
POST http://localhost:3030/v1/api/shop/signup
Content-Type: application/json
x-api-key: "12312"

{
    "name": "phong10",
    "email": "phongdang10@gmail.com",
    "password": "123123@Abc1"
}

###
POST http://localhost:3030/v1/api/shop/login
Content-Type: application/json
x-api-key: "12312"

{
    "email": "phongdang10@gmail.com",
    "password": "123123@Abc1"
}